# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\BlackBeard\Desktop\Projects\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Window(object):
    def setupUi(self, Login_Window):
        Login_Window.setObjectName("Login_Window")
        Login_Window.resize(421, 528)
        Login_Window.setMinimumSize(QtCore.QSize(421, 528))
        Login_Window.setMaximumSize(QtCore.QSize(550, 650))
        Login_Window.setWindowOpacity(5.0)
        Login_Window.setStyleSheet("QMainWindow{\n"
"        background-color:rgb(226,226,226);\n"
"}\n"
"\n"
"QLabel#label_login{\n"
"        font-size:60px;\n"
"        font-weight:bold;\n"
"        color:#2c3e50;\n"
"        margin-top:20px;\n"
"        margin-bottom:20px;\n"
"}\n"
"QLineEdit{\n"
"    padding:12px;\n"
"    font-size:20px;\n"
"    border:2px solid #ccc;\n"
"    border-radius:3px;\n"
"    \n"
"\n"
"}\n"
"QPushButton{\n"
" padding:15px;\n"
"font-size:14px;\n"
"font-weight:bold;\n"
"border:3px solid #ccc;\n"
"border-radius:4px;\n"
"\n"
"}\n"
"QPushButton#btn_Login:hover{\n"
"background-color:#44b422;\n"
"}\n"
"QPushButton#btn_Exit:hover{\n"
"background-color:#df0d4c;\n"
"}\n"
"    ")
        self.centralwidget = QtWidgets.QWidget(Login_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_login = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_login.sizePolicy().hasHeightForWidth())
        self.label_login.setSizePolicy(sizePolicy)
        self.label_login.setMinimumSize(QtCore.QSize(0, 0))
        self.label_login.setMaximumSize(QtCore.QSize(600, 175))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_login.setFont(font)
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout.addWidget(self.lineEdit_username)
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Login.setObjectName("btn_Login")
        self.horizontalLayout.addWidget(self.btn_Login)
        self.btn_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Exit.setObjectName("btn_Exit")
        self.horizontalLayout.addWidget(self.btn_Exit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        Login_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login_Window)
        QtCore.QMetaObject.connectSlotsByName(Login_Window)

    def retranslateUi(self, Login_Window):
        _translate = QtCore.QCoreApplication.translate
        Login_Window.setWindowTitle(_translate("Login_Window", "Login"))
        self.label_login.setText(_translate("Login_Window", "LOGIN"))
        self.lineEdit_username.setPlaceholderText(_translate("Login_Window", "Enter username"))
        self.lineEdit_password.setPlaceholderText(_translate("Login_Window", "Enter password"))
        self.btn_Login.setText(_translate("Login_Window", "Login"))
        self.btn_Exit.setText(_translate("Login_Window", "Exit"))
