# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\BlackBeard\Desktop\Projects\app\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MoviesWindow(object):
    def setupUi(self, MoviesWindow):
        MoviesWindow.setObjectName("MoviesWindow")
        MoviesWindow.resize(1404, 694)
        MoviesWindow.setStyleSheet("QMainWindow{\n"
"    background-color:#121212;\n"
"}\n"
"QLabel#label_title{\n"
"    font-size:38px;\n"
"    font-weight:700;\n"
"    color:#f5c518; \n"
"    margin:20px 0;\n"
"}\n"
"QWidget#gridLayoutWidget{\n"
"    background-color:#1e1e1e;\n"
"    border-radius:12px;\n"
"    border:1px solid #2f2f2f;\n"
"    padding:12px;\n"
"}\n"
"QComboBox{\n"
"    background-color:#2a2a2a;\n"
"    color:white;\n"
"    padding:6px 10px;\n"
"    border-radius:6px;\n"
"    border:1px solid #3a3a3a;\n"
"}\n"
"QComboBox::drop-down{\n"
"    width:30px;\n"
"    border-left:1px solid #3a3a3a;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: none;\n"
"    border: none;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"    background-color:#1e1e1e;\n"
"    color:white;\n"
"    selection-background-color:#f5c518;\n"
"    selection-color:black;\n"
"}\n"
"QPushButton{\n"
"    background-color:#f5c518;\n"
"    color:black;\n"
"    font-size:15px;\n"
"    font-weight:600;\n"
"    padding:10px 18px;\n"
"    border-radius:8px;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#ffd84d;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:#e6b800;\n"
"}\n"
"QCheckBox,\n"
"QRadioButton{\n"
"    color:#dddddd;\n"
"    font-size:14px;\n"
"    spacing:6px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QRadioButton::indicator{\n"
"    width:16px;\n"
"    height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked,\n"
"QRadioButton::indicator:checked{\n"
"    background-color:#f5c518;\n"
"    border-radius:3px;\n"
"    color:white;\n"
"}\n"
"QTableWidget{\n"
"    background-color:#181818;\n"
"    color:black;\n"
"    gridline-color:#2f2f2f;\n"
"    border:1px solid #2f2f2f;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color:#1f1f1f;\n"
"    color:#f5c518;\n"
"    font-weight:600;\n"
"    padding:8px;\n"
"    border:none;\n"
"}\n"
"\n"
"QTableWidget::item:selected{\n"
"    background-color:white;\n"
"    color:black;\n"
"}\n"
"QRadioButton:disabled{\n"
"    background-color:#2a2a2a;\n"
"    color:#777;\n"
"    border-radius:3px;\n"
"    padding:4px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MoviesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(450, 10, 501, 111))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("")
        self.label_title.setObjectName("label_title")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(450, 140, 941, 511))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 140, 421, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_genre = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_genre.setObjectName("comboBox_genre")
        self.gridLayout.addWidget(self.comboBox_genre, 1, 0, 1, 1)
        self.checkBox_rating = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_rating.setObjectName("checkBox_rating")
        self.gridLayout.addWidget(self.checkBox_rating, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.checkBox_genre = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_genre.setObjectName("checkBox_genre")
        self.gridLayout.addWidget(self.checkBox_genre, 1, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.radioButton_AllList = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_AllList.setObjectName("radioButton_AllList")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton_AllList)
        self.radioButton_top10 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_top10.setObjectName("radioButton_top10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioButton_top10)
        self.radioButton_top25 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_top25.setObjectName("radioButton_top25")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.radioButton_top25)
        self.radioButton_top50 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_top50.setObjectName("radioButton_top50")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.radioButton_top50)
        self.gridLayout.addLayout(self.formLayout, 0, 2, 3, 1)
        self.comboBox_year = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_year.setObjectName("comboBox_year")
        self.gridLayout.addWidget(self.comboBox_year, 2, 0, 1, 1)
        self.checkBox_year = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_year.setObjectName("checkBox_year")
        self.gridLayout.addWidget(self.checkBox_year, 2, 1, 1, 1)
        self.comboBox_rating = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_rating.setObjectName("comboBox_rating")
        self.gridLayout.addWidget(self.comboBox_rating, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.btn_Show = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_Show.setObjectName("btn_Show")
        self.gridLayout.addWidget(self.btn_Show, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        MoviesWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MoviesWindow)
        QtCore.QMetaObject.connectSlotsByName(MoviesWindow)

    def retranslateUi(self, MoviesWindow):
        _translate = QtCore.QCoreApplication.translate
        MoviesWindow.setWindowTitle(_translate("MoviesWindow", "IMDB Top 250"))
        self.label_title.setText(_translate("MoviesWindow", "IMDB Top 250 Movies"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MoviesWindow", "rank"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MoviesWindow", "name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MoviesWindow", "year"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MoviesWindow", "rating"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MoviesWindow", "genre"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MoviesWindow", "directors"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MoviesWindow", "writers"))
        self.checkBox_rating.setText(_translate("MoviesWindow", "Rating"))
        self.checkBox_genre.setText(_translate("MoviesWindow", "Genre"))
        self.radioButton_AllList.setText(_translate("MoviesWindow", "All List"))
        self.radioButton_top10.setText(_translate("MoviesWindow", "Top 10"))
        self.radioButton_top25.setText(_translate("MoviesWindow", "Top 25"))
        self.radioButton_top50.setText(_translate("MoviesWindow", "Top 50"))
        self.checkBox_year.setText(_translate("MoviesWindow", "Year"))
        self.btn_Show.setText(_translate("MoviesWindow", "Show"))
